### ISSUE TITLE
import weeve VM into virtualbox error

### ISSUE THREAD

**Issue by xzcccc** [weeveiot/weeveOS#2]
I download the weeve-VM by click the url in the README. However when I import the ova file into virtualbox(also in vmware), an errror occur. Is this because the file I downloaded is error file?
And the .ova file md5sum value is:
MD5: 301E1C07812CA98CA686F09A1B124A19
SHA1: 3F14E1CD9898B2D3DAC234597DF6C7EF9C0332A2
CRC32: B968EB6F
Is that correct?

![1527076872 1](https://user-images.githubusercontent.com/26038528/40423118-18835b60-5ec4-11e8-9550-f2f41cd2e834.jpg)

**Comment by sthomsen1** [comment]
Hi xzcccc, what operating system are you running? Win7 32-bit? 
And can you provide us some hardware specification like RAM/CPU.

**Comment by xzcccc** [comment]
Hi sthomsen1, my OS is Win7 64-bit
The CPU: Intel(R) Core(TM) i5-4590 CPU @3.30GHz

**Comment by xzcccc** [comment]
And the RAM is 10GB

**Comment by sthomsen1** [comment]
Which version of virtualbox are you running? We try to reconstruct your problem but everything works from here.

**Comment by xzcccc** [comment]
My virtualbox version is 5.1.6 r110634 (Qt5.5.1)

**Comment by sthomsen1** [comment]
Hey xzcccc, we reproduced your problem! your version of virtualbox is to old. Just update to the newest version and it should work fine.

**Comment by xzcccc** [comment]
OK,it works!!
Thank you very much!
